### ISSUE TITLE
breaks on servers

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Rivmun/SuperFancyCloudsRefabricated#16]
https://mclo.gs/Z7UNuOw

**Comment by coornio** [comment]
Maaaaaaaaaaay wanna post a log when you are only running the bare minimum of mods required to reproduce the crash, as a precaution. There may very well be some conflict, even if it only occurs in multiplayer.

**Comment by Aces-and-Jacks** [comment]
I'll do a bare minimum test and send it later

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/He8f6D2

shorter

**Comment by Aces-and-Jacks** [comment]
dropped a considerable amount of mods but probably not the bare minimum. If you want me to go shorter I can

**Comment by Rivmun** [comment]
I found that the non-host client cannot access to `ServerWorld`. It's private and hidden in server unless I make a little server-side things to send it out. But this is not necessary for a pure client-side visual effect mod.
I'll disable pre-detect feature that depends on `ServerWorld` on non-host client.

**Comment by Aces-and-Jacks** [comment]
So you'll have it completely disabled? 

Or maybe have it disabled for now until maybe adding a function to detect if the mod is being used between client and server? So like if you have it on your own world it'd automatically detect that and enable the feature

**Comment by Rivmun** [comment]
Yep, pre-detect feature only runs when you play with integrated server now.
Specifically, you need in single play, or be the host in multiplayer to use this feature.

**Comment by Aces-and-Jacks** [comment]
Would it be possible to install this mod server side then?

**Comment by Aces-and-Jacks** [comment]
> But this is not necessary for a pure client-side visual effect mod.

Wasn't sure if you meant you weren't going to have it as a server side or leave it as is

**Comment by Rivmun** [comment]
This mod is always client-side only.



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/11/2023 11:50 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [Rivmun/SuperFancyCloudsRefabricated] breaks on servers (Issue #16) |

But this is not necessary for a pure client-side visual effect mod.

Wasn't sure if you meant you weren't going to have it as a server side or leave it as is

**Comment by Rivmun** [comment]
However, if you want to synchronize the cloud between clients connect to a same server (This is a very attractive feature that few mods can achieve it), open a new issue and I'll considering ~~and learn how to do~~ it.😀
