### ISSUE TITLE
[1.18.2] Issues with Clouds, crashes when looking up at the sky. (Mod Incompat?)

### ISSUE THREAD

**Issue by ConqAra** [Rivmun/SuperFancyCloudsRefabricated#20]
Clouds sometimes do not spawn or just behave extremely weird such as refreshing constantly with no weather affected, glitching out when u move while looking at them, and just behaving strange. Most times when joining pre-existing worlds they straight up do not appear at all and will eventually crash the game if you keep looking at the sky

Logs: [https://paste.ee/p/o8aGb](https://paste.ee/p/o8aGb)

**Comment by Rivmun** [comment]
Remove `Cull Clouds` and try again. It author tested with original SuperFancyClouds mod and occur incompatibility.

**Comment by Rivmun** [comment]
> refreshing constantly with no weather affected
Maybe affected by biome change. Try to disable it in config screen -> dynamic density -> biome affect (at bottom of this tab) if you dislike that.
Cloud needs to synchronize with player's position. So it will refresh once instantly when you across chunk border. I have not a good idea can avoid it for now. However, it doesn't cause a crash.

**Comment by ConqAra** [comment]
the player's position thing is a bit weird, because just walking you can see them move along with you and its a bit wonky. anyway to fix this?

**Comment by Rivmun** [comment]
Uhhh, this problem does exist I confirm. It may cause by a position calculation mistake. I'll look into it.
Back to the title, is the crash figure out?

**Comment by ConqAra** [comment]
Yeah, removing cull clouds makes it so it doesnt crash anymore

**Comment by Rivmun** [comment]
I'm open a new issue to focus on that problem that clouds move along with player. This issue will marked as "compatibility" and closed.
