### ISSUE TITLE
[1.19.2] Clouds don't render

### ISSUE THREAD

**Issue by PencilVoid** [Rivmun/SuperFancyCloudsRefabricated#22]
![2023-02-11_15 11 32](https://user-images.githubusercontent.com/83508866/218267499-1d4e234e-88a3-45a9-b26c-8140384ef542.png)
Tested with Quilt Loader 0.18.1-beta.68 and SuperFancyClouds: Refabricated 1.4.1

**Comment by Rivmun** [comment]
Try to do with https://github.com/Rivmun/SuperFancyCloudsRefabricated/issues/19#issuecomment-1426254805.
