### ISSUE TITLE
[Forge-1.20.1]在天气变化时稳定与服务器断连

### ISSUE THREAD

**Issue by Greygreygod** [Rivmun/SuperFancyCloudsRefabricated#76]
MOD版本:sfcr-1.7.5
Forge版本:47.1.0
在服务器里每当天气发生变化时，都会掉线剩一个人，在客户端去掉该MOD后就不会出现。
没有产生崩溃所以没有crash_report，log和debug也没有相关的记录，所以无法提供。
![OPAERYVW_{0~ET($M(84H8T](https://github.com/Rivmun/SuperFancyCloudsRefabricated/assets/61723789/afb6cccd-1e0f-4c03-967e-5bdc2727b5bc)

**Comment by Rivmun** [comment]
意思是服务端安装了sfcr，然后所有安装了sfcr的客户端在天气变化的时候只能有一个人能稳定连接？去掉sfcr的客户端不受影响？

**Comment by Greygreygod** [comment]
是的，我现在服务端还装载着sfcr，只要客户端去掉sfcr就不会断连，后面也试验到只有还装着sfcr的客户端会受到影响。
这个latest是我进服之后手动改的天气，可以搜索从'Greygod:1'那边开始看。
[latest.log](https://github.com/Rivmun/SuperFancyCloudsRefabricated/files/11997941/latest.log)

**Comment by Rivmun** [comment]
从日志中初步判断是与 Connectivity 的兼容问题，可尝试移除该模组再试。
至于为什么会冲突还有待研究。

**Comment by Greygreygod** [comment]
Connectivity是我视图解决这个问题的时候加的，我之前以为是packet不够用，在找到原因后忘记卸了。在装Connectivity之前就一直弹我最初发的那张图的错误。
这个问题需要有两个或以上的玩家才会触发，一个人我试过不会触发，这也是为啥我到实际朋友玩才发现这个问题的原因。

**Comment by Rivmun** [comment]
应该已经修好了，晚点会发布更新。

因为我需要将更改同步到其他版本的分支里，正式发布可能还需要一些时间，所以有需要的话可以先在action页面下载最新的构建。

**Comment by Greygreygod** [comment]
好的，辛苦了
