### ISSUE TITLE
[1.20.1] Incompatible with ImmediatelyFast-1.1.25

### ISSUE THREAD

**Issue by qznfbnj** [Rivmun/SuperFancyCloudsRefabricated#88]
## Mod List
![image](https://github.com/Rivmun/SuperFancyCloudsRefabricated/assets/100760086/2ec17bae-faf5-45ca-88b8-bdecd2664c53)
## Description
Install sfcr-1.7.6-mc1.20 and [ImmediatelyFast-1.1.25+1.20.1](https://github.com/RaphiMC/ImmediatelyFast/commit/34dabe8), then cause completely random crash.
sfcr-1.7.6-mc1.20 and ImmediatelyFast-1.1.*24*+1.20.1, no problem.
If it's ImmediatelyFast's fault, inform me, I'll report to their issue tracker.
[crash-2023-08-05_17.14.09-client.txt](https://gist.github.com/qznfbnj/80b57d5ba710755b996d6dd4a794f5c6#file-crash-2023-08-05_17-14-09-client-txt)
[latest.log(crash after F3+G)](https://gist.github.com/qznfbnj/392059e200dc591e102f8001c763e0ab#file-latest-log)
[latest.log(crash on entering world)](https://gist.github.com/qznfbnj/1ac597cd1d66502e2596f0c9599acbf7#file-latest-log)

**Comment by Rivmun** [comment]
Test with `ImmediatelyFast-1.1.26` and it's fine.
