### ISSUE TITLE
How to use as a dependency?

### ISSUE THREAD

**Issue by s5bug** [Rivmun/SuperFancyCloudsRefabricated#90]
I would like to determine whether or not an entity is inside a cloud. How can I do this?

**Comment by Rivmun** [comment]
Temporally, you can use cursemaven https://www.cursemaven.com/, add a SFCR file link which provided by curseforge in build.gradle.
![image](https://github.com/Rivmun/SuperFancyCloudsRefabricated/assets/113169310/38489989-ac58-42c4-9806-05a46dd851cc)

**Comment by s5bug** [comment]
Does CurseMaven work differently from Modrinth Maven? My concern is that this will pull in the merged JAR:

![image](https://github.com/Rivmun/SuperFancyCloudsRefabricated/assets/7751296/8c88a67e-174a-4af0-96c7-a046866df606)

I believe I need the separate `common`/`fabric`/`forge` JARs for an Architectury project. (Which, I'm guessing I could `publishLocal` myself, if the artifact names are set up correctly.)

**Comment by Rivmun** [comment]
Try to use `fabric.com.rimo.sfcr.xxx` or `forge.com.rimo.sfcr.xxx` to access class.

**Comment by Rivmun** [comment]
https://github.com/Rivmun/SuperFancyCloudsRefabricated/blob/fd14f60223334c3344274172ae9104769ddeb32f/common/src/main/java/com/rimo/sfcr/core/CloudData.java#L133C6-L134C6 
As a reference of how to transform a cloudblock pos into blockpos. (Entity pos is blockpos)

**Comment by s5bug** [comment]
This means I would have to duplicate my logic for each platform, right? Considering I have no access to `common` classes?

I don't really mind that, but I want to make sure there's not something I'm unaware of.

**Comment by s5bug** [comment]
How do I grab the `scrollX` and `scrollZ` used in these calculations? And is there a way to get the existing cloud data without recalculating the samples?

**Comment by Rivmun** [comment]
> This means I would have to duplicate my logic for each platform, right? Considering I have no access to `common` classes?
> 
> I don't really mind that, but I want to make sure there's not something I'm unaware of.

Yes, use `fabric` prefix if your project in fabric, elsewise `forge`, or just make a ExpectPlatform` method if you use Architectury.

**Comment by Rivmun** [comment]
> How do I grab the `scrollX` and `scrollZ` used in these calculations? And is there a way to get the existing cloud data without recalculating the samples?

My sorry that you may need to calculate it by yourself for now... See in 
https://github.com/Rivmun/SuperFancyCloudsRefabricated/blob/fd14f60223334c3344274172ae9104769ddeb32f/common/src/main/java/com/rimo/sfcr/core/Renderer.java#L81-L82
I want to make some public method to access cloud data in future version, but it'll no soon.

**Comment by s5bug** [comment]
Ok, thank you very much!

**Comment by s5bug** [comment]
Hmm, the cloud data is supposed to synchronize from server to client, right? What do `xScroll` and `zScroll` do then, if it looks like they're per-player? (i.e. how do I do the query server-side?)

My plan depends on every player being able to see the same (or at least close enough to the same) clouds.

**Comment by s5bug** [comment]
Ah, I see. The math cancels out between `px` including `scrollX` and `getCloudSample` removing it.

**Comment by Rivmun** [comment]
Send whole cloud data will consume lots of network. I've only synchronized sample seed (and most config which affect to visual) and total (and partial) z-offset from server to client. Cloud data calculate by client itself based on these two values.

**Comment by s5bug** [comment]
Yep, I have something that works well now. I've had to reimplement `getDensity` and `getThreshold`, but it works very well.

![image](https://github.com/Rivmun/SuperFancyCloudsRefabricated/assets/7751296/fe79d50d-242d-433a-b926-06a0438af3ca)

Is there any way I can force certain configuration values? I want to make sure
- "Biome Detect From Chunk" is forced on, so that clouds are location-based and not player based
- "Sync With Server" is forced on, so that whatever the server has set is synced to all clients

I've had to run `/sfcr sync full` manually on each client, but I'm assuming I can just force that to happen by adding my own network handler that runs the command (on join?).

**Comment by Rivmun** [comment]
I think you can call `.sfcr.SFCReMod.COMMON_CONFIG.setBiomeDensityUseLoadedChunk(true)` to force turn it on when player join and close config screen (to anti-editing :D
"Sync with Server"? Call `.setEnableServerConfig(true)`

Oh you make a mod that make player can standing on clouds? Awesome!

**Comment by s5bug** [comment]
Not standing on, but fishing from 😄

I'm going to see if I can make the server send the client way more biome data; considering I'm forcing configuration sync, I should be able to send the full render distance of the cloud plane to the client, right? Then I shouldn't have to force `UseLoadedChunk`?

**Comment by Rivmun** [comment]
Maybe. 
Since players have different position, they'll have different loaded chunk. So players from different positions will get different results when looking at the same cloud. Unless you turn off biome affect, or limit cloud render distance to chunk load distance.
