### ISSUE TITLE
Create new world crash

### ISSUE THREAD

**Issue by WenXin20** [Rivmun/SuperFancyCloudsRefabricated#91]
```
Minecraft v1.20.1
Forge v47.2.0
SFCR v1.7.6
```

When creating a new world, I get this crash. The second time I load the world it doesn't crash.
[Crash Report](https://gist.github.com/WenXin20/9077f29cfe2f6cd8e58b47cf3cc5d330)

**Comment by Rivmun** [comment]
I've use minimums mod sets to create a new world both in forge-47.1 and 47.2 but nothing happens.
Seems something makes server tick earlier than world loading when creating worlds. I don't know what exactly mod will cause it.

**Comment by WenXin20** [comment]
It might be Aether that does that, but I'm not sure
