### ISSUE TITLE
OpenGL debug message: id=1281 Log Spam

### ISSUE THREAD

**Issue by setzke** [Rivmun/SuperFancyCloudsRefabricated#92]
EDIT: _I tried to recreate this by having ONLY SuperFancyCloudsRefabricated installed, along with its related dependencies / config mods, **but the issue didn't happen.** So it's interacting with one of the other many mods I have installed. Is there a way to look further into this without just manually turning off each mod one by one?_

 
Fabric
v1.7.6-mc1.20

If "View Culling Angle Multiplier" is not disabled, there is log spam:
`[Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. <size> must be positive.'`

Default:
![image](https://github.com/Rivmun/SuperFancyCloudsRefabricated/assets/13110348/82cdd9f7-12db-408a-8943-9f6306b5b9f7)

Disabled:
![image](https://github.com/Rivmun/SuperFancyCloudsRefabricated/assets/13110348/31d3c25c-f936-4723-b47a-c20bc177bac6)

**Comment by Rivmun** [comment]
OpenGL 1281/1282 or else id is a classical problem in Minecraft. You can check your config of Minecraft itself named by 'option.txt' at Minecraft root folder and find a line with 'glDebugVerbosity', then set it to '0', the GL error message will never show.

Additionally, I've notice that a random crash on 1.18.2 #73 when 'view culling angle multiplier' is not disabled. I'll fix it in next version by let clouds face never be culled to 0.
